site_name: Achterhoek-RP Wetboek
site_url: http://wetboek.achterhoek-rp.nl
site_author: 'Achterhoek-RP'

theme:
  name: material
  language: nl
  logo: img/achterhoek-logo.png
  favicon: img/achterhoek-logo.png
  palette:
      # Light mode
#     - media: "(prefers-color-scheme: light)"
      scheme: default
#       primary: deep orange
#       accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Donkere modus

      # Dark mode
#     - media: "(prefers-color-scheme: dark)"
      scheme: slate
#       primary: deep orange
#       accent: deep orange
      toggle:
        icon: material/weather-night
        name: Lichte modus


copyright: © Achterhoek-RP 2021

google_analytics: ['UA-194031470-1', 'wetboek.achterhoek-rp.nl']

plugins:
  - search:
      lang: nl
  - git-revision-date-localized:
      type: timeago
      time_zone: Europe/Amsterdam
      locale: nl
      fallback_to_build_date: false

nav:
  - Home: index.md
  - Algemene regels: algemeen.md
  - Ingame regels: wetboek.md
  - Streamer regels: streamers.md
  - Discord regels: discord.md

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/zGc3aXu
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/achterhoekrp/
    - icon: fontawesome/solid/globe
      link: https://www.achterhoek-rp.nl
